version: '3.8'

services:
  db:
    image: postgres:16.4-bookworm
    environment:
      POSTGRES_DB: alerthub
      POSTGRES_USER: alertuser
      POSTGRES_PASSWORD: alertpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  alert-hub-go:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: alertuser
      DB_PASS: alertpassword
      DB_NAME: alerthub
      ENCRYPTION_KEY: zTyaSIjTHH1rFjvEOGWhFVp3GmfUxtKT1nmFoLD8wCI= # openssl rand -base64 32
      GIN_MODE: release
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
